#!/bin/bash

echo
echo "########################################################"
echo "####         Create Docker VPN Configuratiom        ####"
echo "########################################################"
echo

source docker/vars

source docker/pre-compose

echo
echo "Create Openvpn Folder..."
mkdir -pv "openvpn"

echo
echo "Generate OpenVPN Config..."
docker run --name $openvpn_data -v /etc/openvpn busybox
docker run --volumes-from $openvpn_data --rm kylemanna/openvpn ovpn_genconfig -u udp://$vpn_url:1194

echo
echo "Generate OpenVPN Keys..."
docker run --volumes-from $openvpn_data --rm -it kylemanna/openvpn ovpn_initpki
docker run --volumes-from $openvpn_data --rm -it kylemanna/openvpn easyrsa build-client-full $application_name nopass
docker run --volumes-from $openvpn_data --rm kylemanna/openvpn ovpn_getclient $application_name > openvpn/$application_name.ovpn

echo
echo "Copy Keys Locally..."
docker cp $openvpn_data:/etc/openvpn ./

# Start VPN
#docker run --volumes-from $openvpn_data --rm -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn