#!/bin/bash

echo
echo "########################################################"
echo "####                Compose Environment             ####"
echo "########################################################"
echo

app_choice="$1"

if [ -z "$app_choice" ]; then
	app_choice="dev"
fi

if [ -z "$machine_name" ]; then
	source docker/vars
fi

echo
echo "Build Docker Images..."
docker-compose -p $application_name -f docker-compose/$app_choice.yml build

echo
echo "Start Docker Images..."
sh docker/bin/osx-dev -r "docker-compose -p $application_name -f docker-compose/$app_choice.yml up" -i ".rsyncignore" -s "./"