#!/bin/bash

echo
echo "########################################################"
echo "####          Install Docker & Dependencies         ####"
echo "########################################################"
echo

# Install/Update Homebrew
if [ ! type brew > /dev/null 2>&1 ] ; then
	echo "Homebrew not found, installing..."
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brew tap homebrew/services
	brew tap homebrew/completions
	brew install bash-completion
	brew install awscli awsebcli
	brew install brew-cask-completion
else
	echo "Homebrew found, updating..."
	brew uninstall --force brew-cask
	brew upgrade; brew update; brew cleanup; brew cask cleanup; brew prune
fi

echo
# Install Node
if [ ! type node > /dev/null 2>&1 ]; then
	brew install node;
else
	echo "Node JS found. skipping installation..."
fi

echo
# Install NPM
if [ ! type npm > /dev/null 2>&1 ]; then
	brew install node --force;
else
	echo "NPM found. Updating Packages..."
	npm install -g npm bower ember-cli strongloop mocha karma jshint eslint csslint
fi

echo
# Install Node / NPM
if [ ! type npm > /dev/null 2>&1 ]; then
	sh bin/create-sercrets-env.sh
else
	echo "Secrets file found. skipping creation..."
fi

echo
# Install Virtualbox
if [ ! type virtualbox > /dev/null 2>&1 ] ; then
	echo "Virtualbox not found, installing..."
	brew cask install virtualbox
else
	echo "Virtualbox found, skipping installation..."
fi

echo
# Install Docker Toolbox ( docker, docker-compose, docker-machine )
if [ ! type docker > /dev/null 2>&1 ] ; then
	echo "Docker Toolbox not found, installing..."
	brew install docker docker-compose docker-machine
else
	echo "Docker Toolbox found, skipping installation..."
fi

echo
# Install Watchman
if [ ! type watchman > /dev/null 2>&1 ] ; then
	echo "Watchman not found, installing..."
	brew install watchman
else
	echo "Watchman found, skipping installation..."
fi

echo
# Install FSwatch
if [ ! type fswatch > /dev/null 2>&1 ] ; then
	echo "FS Watch not found, installing..."
	brew install fswatch
else
	echo "FS Watch found, skipping installation..."
fi

echo
# Install Core Utilities
if [ ! type greadlink > /dev/null 2>&1 ] ; then
	echo "GNU core utilities not found, installing..."
	brew install coreutils
else
	echo "GNU core utilities found, skipping installation..."
fi

echo
# Install GNU Sed command
if [ ! type sed > /dev/null 2>&1 ]; then
	echo "SED command not found, installing..."
	brew install gnu-sed --with-default-names
else
	echo "SED command found, skipping installation..."
fi

echo
# Create SSL Certificates
if [ ! -f sslcert/server.crt ]; then
	sh bin/create-ssl-cert.sh
else
	echo "SSL Certificate found. skipping creation..."
fi

echo
# Create secrets/passwords environment variables
if [ ! -f shared/env/secrets.env ]; then
	sh bin/create-sercrets-env.sh
else
	echo "Secrets file found. skipping creation..."
fi
