#!/bin/bash

echo
echo "########################################################"
echo "####             Start Docker Environment           ####"
echo "########################################################"
echo

app=$1;

if [ -z "$app" ]; then
	app="dev";
fi

source docker/vars

source docker/banner

source docker/pre-compose

source docker/compose $app
