#!/bin/bash

echo
echo "########################################################"
echo "####         Uninstall Docker & Dependencies        ####"
echo "########################################################"
echo

echo
# Uninstall Virtualbox
if type virtualbox > /dev/null 2>&1 ; then
	echo "Virtualbox found, uninstalling..."
	brew cask uninstall --force virtualbox
else
	echo "Virtualbox not found, already uninstalled..."
fi

echo
# Uninstall Docker Toolbox ( docker, docker-compose, docker-machine, docker-machine-parallels )
if type docker > /dev/null 2>&1 ; then
	echo "Docker Toolbox found, uninstalling..."
	brew uninstall --force docker-machine-parallels
	brew uninstall --force docker docker-compose docker-machine
else
	echo "Docker Toolbox not found, already uninstalled..."
fi

echo
# Uninstall Watchman
if type fswatch > /dev/null 2>&1 ; then
	echo "Watchman found, uninstalling..."
	brew uninstall --force watchman
else
	echo "Watchman not found, already uninstalled..."
fi

echo
# Uninstall FSwatch
if type fswatch > /dev/null 2>&1 ; then
	echo "FS Watch found, uninstalling..."
	brew uninstall --force fswatch
else
	echo "FS Watch not found, already uninstalled..."
fi

echo
# Uninstall Core Utilities
if type greadlink > /dev/null 2>&1 ; then
	echo "GNU core utilities found, uninstalling..."
	brew uninstall --force coreutils
else
	echo "GNU core utilities not found, already uninstalled..."
fi

echo
# Uninstall GNU Sed command
if [ ! type sed > /dev/null 2>&1 ]; then
	echo "SED command found, uninstalling..."
	brew uninstall --force gnu-sed
else
	echo "SED command not found, already uninstalled..."
fi
