version: '2'
volumes:
    tmp: {}
    database_data: {}
services:
    database:
        build:
            context: ../database
            dockerfile: Dockerfile
        volumes:
            - database_data:/var/lib/postgresql
            - ../shared:/var/app/current/shared
            - /var/log/postgresql
        ports:
            - 5432
        extends:
            service: base
            file: ../shared/base.yml
    api:
        privileged: true
        command: bash -c "sysctl -w fs.inotify.max_user_watches=1048576 && gulp serve 2>&1 | tee -a /var/log/api/api.log"
        build:
            context: ../api
            dockerfile: Dockerfile
        volumes:
            - /var/app/current/api/bower_components
            - ../sslcert:/var/app/current/sslcert
            - /var/app/current/api/node_modules
            - ../shared:/var/app/current/shared
            - ../api:/var/app/current/api
            - /var/log/api
            - /tmp/api
        depends_on:
            - database
        ports:
            - 3000
            - 9999
        extends:
            service: base
            file: ../shared/base.yml
    server:
        build:
            context: ../nginx
            dockerfile: Dockerfile
        volumes:
            - ../security:/var/app/current/security
            - ../sslcert:/var/app/current/sslcert
            - ../shared:/var/app/current/shared
            - ../nginx:/etc/nginx
            - /var/log/nginx
            - tmp:/tmp
        volumes_from:
            - api
            - database
        ports:
            - 80:80
            - 443:443
            - 5432:5432
            - 38100:38100
            - 39100:39100
        extends:
            service: base
            file: ../shared/base.yml
    registrator:
        image: devotox/registrator
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        depends_on:
            - consul
        links:
            - consul
        extends:
            service: base
            file: ../shared/base.yml
    consul:
        command: -data-dir=/data -ui-dir=/ui -server -bootstrap
        image: progrium/consul
        ports:
            - 53
            - 8301
            - 8302
            - 8300
            - 8400
            - 8500
            - 53/udp
            - 8301/udp
            - 8302/udp
        extends:
            service: base
            file: ../shared/base.yml
    consul-template:
        image: devotox/consul-template
        command: >
            -consul consul:8500
            -template /etc/nginx/templates/upstream_servers.ctmpl:/etc/nginx/conf.d/upstream_servers.conf
            -template /etc/nginx/templates/upstream_stream_servers.ctmpl:/etc/nginx/conf.d/streams/upstream_servers.conf
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        volumes_from:
            - server
        depends_on:
            - consul
            - registrator
        links:
            - consul
        extends:
            service: base
            file: ../shared/base.yml
