# Base Image to use
FROM consul:0.7.5

# File Author / Maintainer
MAINTAINER Devonte Emokpae

# Set environment variables
ENV TERM "xterm"

CMD ["agent", "-server", "-bootstrap", "-client", "0.0.0.0"]
