version: '2'
services:
    base:
        environment:
            - DOCKER_HOST_IP=$DOCKER_HOST_IP
        env_file:
            - env/aws.env
            - env/common.env
            - env/services.env
            - env/htaccess.env
            - env/database.env
            - env/customer.io.env
            - env/secrets.env