#!/bin/bash

echo
echo "########################################################"
echo "####           Start Docker API Environment         ####"
echo "########################################################"
echo

source docker/vars

source docker/banner

source docker/pre-compose

source docker/compose api
