#!/bin/bash

echo
echo "########################################################"
echo "####             Deploy Docker Images               ####"
echo "########################################################"
echo

source docker/deploy/vars

echo
echo "Pull Previous Images from Docker Hub..."
sh docker/deploy/pull

echo
echo "Push New Images to Docker Hub..."
sh docker/deploy/push

echo
echo "Deploy Application..."
source docker/deploy/app