#!/bin/bash

echo
echo "########################################################"
echo "####          Initialize Docker Deploy AWS          ####"
echo "########################################################"
echo

source docker/deploy/vars

echo
echo "Start Machine..."
docker-machine start $machine_name

echo
echo "Attach Machine to Terminal..."
eval $(docker-machine env --shell bash $machine_name)

echo
echo "Setup Git..."
sh docker/deploy/run "bash docker/deploy/create/git-config"

echo
echo "Setup AWS..."
sh docker/deploy/run "aws configure"

echo
echo "Setup Elastic Beanstalk..."
sh docker/deploy/run "eb init"

echo
echo "Login To Elastic Container Registry..."
sh docker/deploy/run "\$(aws --region us-east-1 ecr get-login)"
