#!/bin/bash

echo
echo "########################################################"
echo "####          Initialize Docker Deploy AWS          ####"
echo "########################################################"
echo

source docker/deploy/vars

echo
echo "Setup Git..."
sh docker/deploy/run "bash docker/deploy/git-config"

echo
echo "Setup AWS..."
sh docker/deploy/run "aws configure"

echo
echo "Setup Elastic Beanstalk..."
sh docker/deploy/run "eb init"

echo
echo "Login To Docker Hub..."
sh docker/deploy/run "\$(docker login)"