#!/bin/bash

echo
echo "########################################################"
echo "####              Pull Docker Images                ####"
echo "########################################################"
echo

source docker/deploy/vars

echo
echo "Pull Images from Docker Hub..."
sh docker/deploy/run "docker pull $repository_url/node:latest"
sh docker/deploy/run "docker pull $repository_url/jenkins:latest"
sh docker/deploy/run "docker pull $repository_url/registrator:latest"

echo
echo "Tag Images from Docker Hub..."
sh docker/deploy/run "docker tag $repository_url/node:latest docker_node:latest"
sh docker/deploy/run "docker tag $repository_url/jenkins:latest docker_jenkins:latest"
sh docker/deploy/run "docker tag $repository_url/registrator:latest docker_registrator:latest"

echo
echo "Build Images..."
docker-compose build

echo
echo "Clean Images..."
source docker/deploy/clean

echo
echo "List Images..."
sh docker/deploy/run "docker images"