#!/bin/bash

echo
echo "########################################################"
echo "####              Pull Docker Images                ####"
echo "########################################################"
echo

source docker/deploy/vars

source docker/deploy/pre-compose

echo
echo "Pull Images from ECR..."
sh docker/deploy/run "docker pull ${repository_url}/${application_name}_intranet:latest"
sh docker/deploy/run "docker pull ${repository_url}/${application_name}_website:latest"
sh docker/deploy/run "docker pull ${repository_url}/${application_name}_jenkins:latest"
sh docker/deploy/run "docker pull ${repository_url}/${application_name}_server:latest"
sh docker/deploy/run "docker pull ${repository_url}/${application_name}_api:latest"

echo
echo "Tag Images from ECR..."
sh docker/deploy/run "docker tag ${repository_url}/${application_name}_intranet:latest ${application_name}_intranet:latest"
sh docker/deploy/run "docker tag ${repository_url}/${application_name}_website:latest ${application_name}_website:latest"
sh docker/deploy/run "docker tag ${repository_url}/${application_name}_jenkins:latest ${application_name}_jenkins:latest"
sh docker/deploy/run "docker tag ${repository_url}/${application_name}_server:latest ${application_name}_server:latest"
sh docker/deploy/run "docker tag ${repository_url}/${application_name}_api:latest ${application_name}_api:latest"

echo
echo "Build Images..."
docker-compose -p $application_name -f docker-compose/prod.yml build
docker-compose -p $application_name -f docker-compose/jenkins.yml build

echo
echo "Clean Images..."
source docker/deploy/clean

echo
echo "List Images..."
sh docker/deploy/run "docker images"