#!/bin/bash

echo
echo "########################################################"
echo "####              Push Docker Images                ####"
echo "########################################################"
echo

source docker/deploy/vars

echo
echo "Build Images..."
docker-compose build

echo
echo "Tag Images for Docker Hub..."
sh docker/deploy/run "docker tag docker_node:latest $repository_url/node:latest"
sh docker/deploy/run "docker tag docker_jenkins:latest $repository_url/jenkins:latest"
sh docker/deploy/run "docker tag docker_registrator:latest $repository_url/registrator:latest"

echo
echo "Push Images to Docker Hub..."
sh docker/deploy/run "docker push $repository_url/node:latest"
sh docker/deploy/run "docker push $repository_url/jenkins:latest"
sh docker/deploy/run "docker push $repository_url/registrator:latest"

echo
echo "Clean Images..."
source docker/deploy/clean

echo
echo "List Images..."
sh docker/deploy/run "docker images"