#!/bin/bash

echo
echo "########################################################"
echo "####              Push Docker Images                ####"
echo "########################################################"
echo

source docker/deploy/vars

echo
echo "Build Images..."
docker-compose -p $application_name -f docker-compose/prod.yml build

echo
echo "Tag Images for ECR..."
sh docker/deploy/run "docker tag ${application_name}_intranet:latest ${repository_url}/${application_name}_intranet:latest"
sh docker/deploy/run "docker tag ${application_name}_website:latest ${repository_url}/${application_name}_website:latest"
sh docker/deploy/run "docker tag ${application_name}_server:latest ${repository_url}/${application_name}_server:latest"
sh docker/deploy/run "docker tag ${application_name}_api:latest ${repository_url}/${application_name}_api:latest"

echo
echo "Push Images to ECR..."
sh docker/deploy/run "docker push ${repository_url}/${application_name}_intranet:latest"
sh docker/deploy/run "docker push ${repository_url}/${application_name}_website:latest"
sh docker/deploy/run "docker push ${repository_url}/${application_name}_server:latest"
sh docker/deploy/run "docker push ${repository_url}/${application_name}_api:latest"

echo
echo "Clean Images..."
source docker/deploy/clean

echo
echo "List Images..."
sh docker/deploy/run "docker images"