#!/bin/bash

echo
echo "########################################################"
echo "####          Elastic Beanstalk SSH Server          ####"
echo "########################################################"
echo

source docker/deploy/vars

sh docker/deploy/run "eb ssh $@"