#!/bin/bash

echo
echo "########################################################"
echo "####         Stop Docker Deploy Environment         ####"
echo "########################################################"
echo

source docker/deploy/vars

echo
echo "Stop Containers..."
docker stop $(docker ps -aq)

echo
echo "Clean Containers..."
source docker/deploy/clean

echo
echo "Stop Machine..."
docker-machine stop $machine_name