#!/bin/bash

echo
echo "########################################################"
echo "####       Create Base Dockerrun.aws.json file      ####"
echo "########################################################"
echo

source docker/deploy/vars

source=$1
destination="aws/aws.json"

if [ -z "$source" ]
then
	source="docker-compose.yml"
fi

echo
echo "Creating Configuration for $source @ $destination..."
cat "$source" | docker run --rm -i micahhausler/container-transform > $destination