#!/bin/bash

echo
echo "########################################################"
echo "####          Initialize Docker Deploy GIT          ####"
echo "########################################################"
echo

source docker/deploy/vars

# Check if config already exists
name="$(git config user.name)"
email="$(git config user.email)"

# Prompt for name and email
if [ -z "$name$email" ]; then
	echo "Retrieving GIT details..."
fi

if [ -z "$name" ]; then
	read -p "Your Name: " name;
fi

if [ -z "$email" ]; then
	read -p "Your Email: " email;
fi

if [ -z "$name$email" ]; then
	echo "Must set up git config";
	exit 1;
fi

# Set it to the global config
echo "Setting GIT details..."
git config --global user.name $name
git config --global user.email $email